print('Hello, welcome to Python')
print('What is your name')
myName=input()
print('Hi '+myName,'It is nice to meet you')
print('The length of your name is')
print(len(myName))
print()
print('What is your age?')
myAge = input()
print('You will be '+str(int(myAge)+1)+' next year')
